language: node_js
branches:
  only:
    - test
    - active
    - master
install:
  - npm i
  - npm i -g batshit
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
